code/webapp/core/urls.py
from django.conf.urls import url
from django.contrib.auth import views as auth_views
from django.conf import settings

from .forms.account import LoginForm
from .views import account, dashboard, alert, asset, plots, variable, plot

urlpatterns = [

    # /account
    url(r'^account/login/?$',
        auth_views.login,
        {
            'template_name': 'account/login.html',
            'authentication_form': LoginForm,
        },
        name='account.login'),
    url(r'^account/logout/?$', auth_views.logout, {'next_page':settings.LOGIN_URL}, name='account.logout'),
    url(r'^account/myaccount/?$', account.my_account, name='account.my_account'),
    url(r'^account/preferences/?$', account.preferences, name='account.preferences'),
    url(r'^account/users/?$', account.users, name='account.users'),
    url(r'^account/default', account.default_page, name='account.default'),
    url(r'^account/edit_user/(?P<user_id>[^/.]*)/?', account.my_account, name='account.edit_user'),
    url(r'^account/add_user/?', account.my_account, name='account.add_user'),
    url(r'^account/delete_user', account.delete_user, name='account.delete_user'),
    url(r'^account/ajax/users', account.user_list, name='account.user_list'),

    # /dashboard
    url(r'^hotlist/?$', dashboard.overview, name='overview'),
    url(r'^dashboard/?$', dashboard.default_check, name='default_check'),
    url(r'^system/(?P<group_id>\d+)?$', dashboard.system_overview, name='dashboard.system_overview'),
    url(r'^system/ajax/system_overview_preference', dashboard.update_system_overview_preference, name='dashboard.update_system_overview_preference'),
    url(r'^system/power/(?P<platform_id>[^/.]+)/?', dashboard.power_details, name='dashboard.power_details'),
    url(r'^system/ajax/update_alert_disposition', dashboard.update_alert_by_disposition, name='dashboard.update_alert_by_disposition'),

    url(r'^system/backup_database', dashboard.backup_database, name='dashboard.backup_database'),
    url(r'^system/execute_backup_database', dashboard.execute_backup_database, name='dashboard.execute_backup_database'),

    # /alert
    url(r'^alert/resolve/(?P<alert_id>[^/.]+)/?', alert.resolve_alert_view, name='alert.resolve'),
    url(r'^alert/acknowledge/?', alert.acknowledge, name='alert.acknowledge'),
    url(r'^alert/update_status/?', alert.update_status, name='alert.update_status'),
    url(r'^alert/(?P<alert_id>\d+)/$', alert.detail, name='alert.detail'),
    url(r'^alert/(?P<alert_id>\d+)/(?P<is_resolve>[^/.]+)/?', alert.detail, name='alert.detail'),
    url(r'^alert/save_note/(?P<alert_id>\d+)/?', alert.save_note, name='alert.save_note'),
    url(r'^alert/ajax/get_notes/(?P<alert_id>\d+)/?', alert.get_notes, name='alert.get_notes'),
    url(r'^alert/ajax/get_occurrences/(?P<alert_id>\d+)/?', alert.get_occurrences, name='alert.get_occurrences'),
    url(r'^alert/ajax/view_trigger/(?P<trigger_id>[^/.]+)/?', alert.view_trigger, name='alert.view_trigger'),
    url(r'^alert/ajax/hotlist_alert_list/(?P<user_id>[^/.]+)/?', alert.hotlist_alert_list, name='alert.hotlist_alert_list'),
    url(r'^alert/create_manual/(?P<asset_id>[^/.]+)/(?P<deployment_code>[^/.]+)/?', alert.create_manual, name='alert.create_manual'),
    url(r'^alert/manage_subscriptions/(?P<asset_id>\d+)/?', alert.manage_subscriptions, name='alert.manage_subscriptions'),
    url(r'^alert/edit_trigger/(?P<trigger_id>\w+)/(?P<asset_id>\w+)/$', alert.edit_trigger, name='alert.edit_trigger'),
    url(r'^alert/edit_trigger/(?P<trigger_id>[^/.]+)/?', alert.edit_trigger, name='alert.edit_trigger'),
    url(r'^alert/edit_trigger/?$', alert.edit_trigger, name='alert.edit_trigger'),
    url(r'^alert/clone_trigger/(?P<trigger_id>[^/.]+)/?', alert.clone_trigger_page, name='alert.clone_trigger_page'),
    url(r'^alert/execute_clone_trigger/?', alert.execute_clone_trigger, name='alert.execute_clone_trigger'),
    url(r'^alert/manage_triggers/?$', alert.manage_triggers, name='alert.manage_triggers'),
    url(r'^alert/ajax/trigger_list/?$', alert.trigger_list, name='alert.trigger_list'),
    url(r'^alert/ajax/delete_trigger/?$', alert.delete_trigger, name='alert.delete_trigger'),
    url(r'^alert/ajax/purge_trigger/?$', alert.purge_trigger, name='alert.purge_trigger'),
    url(r'^alert/ajax/trigger_variable_list/(?P<trigger_id>[^/.]+)/?', alert.trigger_variable_list, name='alert.trigger_variable_list'),
    url(r'^alert/ajax/saved_variable_list/?', alert.saved_variables_list, name='alert.saved_variables_list'),
    url(r'^alert/ajax/alert_notification_list/(?P<alert_id>[^/.]+)/?', alert.alert_notification_list, name='alert.alert_notification_list'),
    url(r'^alert/ajax/hotlist_alert_list/(?P<user_id>[^/.]+)/?', alert.hotlist_alert_list, name='alert.hotlist_alert_list'),
    url(r'^alert/ajax/get_trigger_by_id/(?P<trigger_id>[^/.]+)/?', alert.get_trigger_by_id, name='alert.get_trigger_by_id'),
    url(r'^alert/create_redmine_issue/(?P<alert_id>\d+)/?$', alert.create_redmine_issue, name='alert.create_redmine_issue'),
    url(r'^alert/confirm_redmine_issue/(?P<alert_id>\d+)/?$', alert.confirm_redmine_issue, name='alert.confirm_redmine_issue'),
    url(r'^alert/ajax/redmine_trackers/(?P<project_id>\d+)/?$', alert.redmine_trackers, name='alert.redmine_trackers'),
    url(r'^alert/ajax/redmine_tracker_details/(?P<tracker_id>\d+)/?$', alert.redmine_tracker_details, name='alert.redmine_tracker_details'),
    url(r'^alert/ajax/refresh_notifications/?', alert.refresh_notifications, name='alert.refresh_notifications'),
    url(r'^redmine/confirm_redmine_issue/(?P<issue_id>\d+)/?$', alert.confirm_redmine, name='redmine.confirm_redmine'),

    # /asset
    url(r'^asset/overview/(?P<asset_id>[^/.]+)/(?P<deployment_code>[^/.]+)/?', asset.overview, name='asset.overview'),
    url(r'^asset/group/(?P<group_id>[^/.]+)/?', asset.group_overview, name='asset.group_overview'),
    url(r'^asset/map/(?P<group_id>[^/.]+)/?', asset.group_mooring_locations, name='asset.group_mooring_locations'),
    url(r'^asset/plot-data/?', asset.plot_data, name='asset.plot_data'),
    url(r'^asset/ajax/alert_history_data', asset.ajax_alert_history_data, name='asset.ajax_alert_history_data'),
    url(r'^asset/ajax/status_history_data/(?P<asset_id>\d+)', asset.ajax_status_history_data, name='asset.ajax_status_history_data'),
    url(r'^asset/picker/(?P<asset_id>[^/.]+)/(?P<name>[^/.]+)/?', asset.picker, name='asset.picker'),
    url(r'^asset/status_grid/(?P<platform_id>\d+)', asset.status_grid, name='asset.status_grid'),
    url(r'^asset/gliders/(?P<group_id>\d+)', asset.glider_overview, name='asset.glider_overview'),
    url(r'^asset/clone/(?P<asset_id>[^/.]+)/?', asset.clone_asset, name='asset.clone_asset'),
    url(r'^asset/execute_clone_asset/?', asset.execute_clone_asset, name='asset.execute_clone_asset'),
    url(r'^asset/purge_asset/(?P<asset_id>[^/.]+)/(?P<deployment_code>[^/.]+)/?', asset.purge_asset, name='asset.purge_asset'),
    url(r'^asset/execute_purge_asset/?', asset.execute_purge_asset, name='asset.execute_purge_asset'),
    url(r'^asset/platforms/?', asset.manage_platforms, name='asset.manage_platforms'),
    url(r'^asset/edit_platform/(?P<platform_id>\d+)', asset.edit_platform, name='asset.edit_platform'),
    url(r'^asset/edit_platform//?', asset.edit_platform, name='asset.edit_platform'),
    url(r'^asset/ajax/platform_list', asset.platform_list, name='asset.platform_list'),
    url(r'^asset/ajax/asset_subcategories', asset.subcategories, name='asset.subcategories'),
    url(r'^asset/import-platform', asset.import_platform, name='asset.import_platform'),
    url(r'^asset/ajax/reload-configuration', asset.reload_configuration, name='asset.reload_configuration'),
    url(r'^asset/ajax/purge-alerts', asset.purge_alerts, name='asset.purge_alerts'),
    url(r'^asset/edit-dataset/(?P<asset_id>[^/.]+)/(?P<deployment_code>[^/.]+)/?', asset.edit_dataset, name='asset.edit_dataset'),
    url(r'^asset/ajax/asset_variables', asset.asset_variables, name='asset.asset_variables'),
    url(r'^asset/ajax/update_erddap', asset.update_erddap, name='asset.update_erddap'),

    # /plot
    url(r'^asset/ajax/get_asset_variables/?', plots.get_asset_variables, name='plots.get_asset_variables'),
    url(r'^asset/ajax/delete_custom_plot/?', plots.delete_custom_plot, name='plots.delete_custom_plot'),
    url(r'^asset/edit_plot/(?P<asset_id>[^/.]+)/(?P<deployment_code>[^/.]+)/?$',plots.edit_plot, name='plots.edit_plot'),
    url(r'^asset/edit_plot/(?P<asset_id>[^/.]+)/(?P<deployment_code>[^/.]+)/(?P<plot_id>[^/.]+)/?',plots.edit_plot, name='plots.edit_plot'),
    url(r'^asset/clone_plot/(?P<asset_id>[^/.]+)/(?P<deployment_code>[^/.]+)/(?P<plot_id>[^/.]+)/?',plots.clone_plot_page, name='plots.clone_plot_page'),
    url(r'^plot/execute_clone_plot/?', plots.execute_clone_plot, name='plots.execute_clone_plot'),
    url(r'^plot/manage_plots/?',plots.manage_plots, name='plots.manage_plots'),
    url(r'^plot_list/ajax/plot_list/?', plots.plot_list, name='plots.plot_list'),
    url(r'^get_plot_info/ajax/get_plot_info/?', plots.get_plot_info, name='plots.get_plot_info'),

    # /plot pages
    url(r'^asset/plot_list/(?P<asset_id>[^/.]+)', plot.plot_list, name='plot.plot_list'),
    url(r'^asset/save_plot_page', plot.save_plot_page, name='plot.save_plot_page'),
    url(r'asset/plot_page/(?P<plot_page_id>[^/.]+)/?', plot.plot_page, name='plot.plot_page'),
    url(r'plot/shared/(?P<share_code>[^/.]+)', plot.plot_page, name='plot.shared_plot_page'),
    url(r'asset/import_plot_page', plot.import_plot_page, name='plot.import_plot_page'),
    url(r'asset/ajax/share_plot_page', plot.share_plot_page, name='plot.share_plot_page'),
    url(r'asset/ajax/disable_sharing', plot.disable_sharing, name='plot.disable_sharing'),
    url(r'^asset/ajax/plot_list_by_asset', plot.plot_list_by_asset, name='plot.plot_list_by_asset'),
    url(r'^plot_page/ajax/delete_plot_page', plot.delete_plot_page, name='plot.delete_plot_page'),

code/webapp/webapp/urls.py
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.contrib import admin
from django.http import HttpResponseRedirect
from django.conf import settings

urlpatterns = [
    url(r'^$', lambda r: HttpResponseRedirect(settings.DASHBOARD_URL)),
    url(r'^admin/', admin.site.urls),
    url(r'^settings/', include('livesettings.urls')),
    url(r'^', include('core.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

code/webapp/core/models/alert.py
from enum import Enum

from django.db import models
from django.contrib.auth.models import User
from .alert_trigger import Trigger
from .static import Statuses, Status, Severities, Severity, DeliveryMethod, DeliveryMethods
from ..models.asset import Asset, Deployment
from ..ui import get_alert_bar_css_class, get_alert_css_class
from ..db import exec_dict, exec_scalar, exec_void
from ..util import enum_choices


class Alert(models.Model):
    created = models.DateTimeField(auto_now_add=True)
    modified = models.DateTimeField(auto_now=True)
    trigger = models.ForeignKey(Trigger, null=True, blank=True)
    status = models.ForeignKey(Status, limit_choices_to=enum_choices(Statuses))
    operational_pct = models.DecimalField(decimal_places=3, max_digits=6, default=0)
    severity = models.ForeignKey(Severity, limit_choices_to=enum_choices(Severities), null=True, blank=True)
    asset = models.ForeignKey(Asset)
    deployment = models.ForeignKey(Deployment)
    details = models.TextField(null=True, blank=True)
    is_manual = models.BooleanField(null=False, blank=False, default=False)
    name = models.CharField(max_length=100, blank=True, null=True)
    last_occurrence = models.DateTimeField(null=True, blank=True)
    roll_up = models.BooleanField(default=False)
    roll_down = models.BooleanField(default=False)
    redmine_id = models.IntegerField(null=True, blank=True)

    def get_hotlist_alerts(self, user_id):
        data = exec_dict('get_hotlist_alerts', (user_id,))

        return [dict(row, css_class=get_alert_bar_css_class(row['severity_id'])) for row in data]

    def get_highest_alert_severity_for_asset(self, asset_id):
        return exec_scalar('get_highest_alert_severity_for_asset', (asset_id,))

    def add_alert_notifications(self, alert_id):
        exec_void('add_alert_notifications', (alert_id,))

    # TODO(mchagnon): We could use a better name than "value"
    def get_status_from_value(self, value):
        return exec_scalar('get_status_from_value', (value,))

    @property
    def alert_css_class(self):
        return get_alert_css_class(self.severity.id)

    @property
    def bar_css_class(self):
        return get_alert_bar_css_class(self.severity.id)

    class Meta:
        db_table = 'alert'

    def get_pending_notifications_for_digest(self, selected_date=None):
        if selected_date is None:
            return exec_dict('get_pending_notifications_for_digest', ())
        else:
            return exec_dict('get_pending_notifications_for_digest', (selected_date,))

    @staticmethod
    def delete(alert_id):
        exec_void("delete_alert", (alert_id, ))


class Note(models.Model):
    created = models.DateTimeField(auto_now_add=True)
    modified = models.DateTimeField(auto_now=True)
    alert = models.ForeignKey(Alert)
    user = models.ForeignKey(User)
    details = models.TextField()

    class Meta:
        db_table = 'alert_note'


class Occurrence(models.Model):
    created = models.DateTimeField()
    alert = models.ForeignKey(Alert)

    # TODO(mchagnon): Deprecated; needs to be removed once any code using it is removed
    triggered_value = models.TextField()

    class Meta:
        db_table = 'alert_occurrence'

class OccurrenceItem(models.Model):
    occurrence = models.ForeignKey(Occurrence)
    occurred_at = models.DateTimeField()

    # TODO: We might need to come back to this and update the precision/length
    value = models.DecimalField(decimal_places=8, max_digits=18)

    class Meta:
        db_table = 'alert_occurrence_item'


class History(models.Model):
    created = models.DateTimeField(auto_now_add=True)
    modified = models.DateTimeField(auto_now=True)
    alert = models.ForeignKey(Alert)
    severity = models.ForeignKey(Severity, limit_choices_to=enum_choices(Severities), null=True, blank=True)
    user = models.ForeignKey(User)

    # TODO(mchagnon): flush this field out
    triggered_value = models.TextField()

    class Meta:
        db_table = 'alert_history'


class Notification(models.Model):
    created = models.DateTimeField(auto_now_add=True)
    modified = models.DateTimeField(auto_now=True)
    alert = models.ForeignKey(Alert)
    user = models.ForeignKey(User)
    has_acknowledged = models.BooleanField(default=False)
    delivery_method = models.ForeignKey(DeliveryMethod, limit_choices_to=enum_choices(DeliveryMethods), null=True, blank=True)

    class Meta:
        db_table = 'alert_notification'


class AlertStatuses(Enum):
    OPEN = 1
    RESOLVED = 4

code/webapp/core/models/redmine.py
from django.db import models


class Project(models.Model):
    name = models.CharField(max_length=50, null=False, blank=False)
    external_id = models.IntegerField(null=False, blank=False)

    def __str__(self):
        return self.name

    class Meta:
        db_table = 'redmine_project'


class Tracker(models.Model):
    name = models.CharField(max_length=50, null=False, blank=False)
    external_id = models.IntegerField(null=False, blank=False)
    project = models.ForeignKey(Project, null=False, blank=False)

    def __str__(self):
        return self.name

    class Meta:
        db_table = 'redmine_tracker'

class Priority(models.Model):
    name = models.CharField(max_length=50, null=False, blank=False)
    external_id = models.IntegerField(null=False, blank=False)
    is_default = models.BooleanField(default=False, null=False, blank=False)

    def __str__(self):
        return self.name

    class Meta:
        db_table = 'redmine_priority'

class Organization(models.Model):
    name = models.CharField(max_length=50, null=False, blank=False)

    def __str__(self):
        return self.name

    class Meta:
        db_table = 'redmine_organization'


class Location(models.Model):
    name = models.CharField(max_length=50, null=False, blank=False)

    def __str__(self):
        return self.name

    class Meta:
        db_table = 'redmine_location'


class Condition(models.Model):
    name = models.CharField(max_length=50, null=False, blank=False)

    def __str__(self):
        return self.name

    class Meta:
        db_table = 'redmine_condition'


class Platform(models.Model):
    name = models.CharField(max_length=50, null=False, blank=False)

    def __str__(self):
        return self.name

    class Meta:
        db_table = 'redmine_platform'

class TrackerField(models.Model):
    name = models.CharField(max_length=50, null=False, blank=False)
    tracker = models.ForeignKey(Tracker, null=False, blank=False)

    def __str__(self):
        return self.name

    class Meta:
        db_table = 'redmine_tracker_field'

class CustomField(models.Model):
    name = models.CharField(max_length=50, null=False, blank=False)
    external_id = models.IntegerField(null=False, blank=False)
    
    def __str__(self):
        return self.name

    class Meta:
        db_table = 'redmine_custom_field'

code/webapp/templates/alert/confirm_redmine_issue.html
{% extends 'base.html' %}
{% load static ui_tags %}

{% block topnav %}

<h1>Create Redmine Issue</h1>
{% endblock %}

{% block content %}

<div id="redmine-issue" class="x_panel">
    <div class="x_content">

        <div class="alert alert-success">
            {% if alert %}
            A Redmine issue for this alert has been created successfully
            {% else %}
            A Redmine issue has been created successfully
            {% endif %}
        </div>



        <div class="row">
            {% if alert %}
            <a href="{% url 'alert.detail' alert.id %}" class="btn btn-default">Return to Alert</a>
            <a href="{{ redmine_url }}/issues/{{ alert.redmine_id }}" class="btn btn-primary" target="_blank">View Issue</a>
            {% else %}
            <a href="/dashboard" class="btn btn-default">Return to Dashboard</a>
            <a href="{{ redmine_url }}/issues/{{ issue_id }}" class="btn btn-primary" target="_blank">View Issue</a>
            {% endif %}
        </div>
    </div>
</div>

{% endblock %}

code/webapp/templates/alert/create_manual.html
{% extends 'base.html' %}
{% load static %}
{% load ui_tags %}

{% block topnav %}
<h1>Create Manual Alert</h1>
{% endblock %}

{% block content %}

{% asset_nav asset.id deployment.code plot_pages current_asset_page %}

<div id="manual-alert" class="x_panel">
    <div class="x_content">

        <form method="post" class="form-horizontal form-label-left" id="manual_alert_form">
            {% csrf_token %}
            {{ form.asset }}
            {{ form.deployment }}
            <div class="row">
                <div class="col-md-2">
                    <div class="form-group">
                        <label class="control-label">{{ form.asset.label_tag }}</label>
                        <div>{{ asset.code }}</div>
                    </div>
                    <div class="form-group">
                        <label class="control-label">{{ form.deployment.label_tag }}</label>
                        <div>{{ deployment.code }}</div>
                    </div>
                    <div class="form-group">
                        <label class="control-label">{{ form.trigger.label_tag }} <span
                                class="required">*</span></label>
                        <div>
                            {{ form.trigger }}
                            <a id="view-trigger" class="hide" href="#"><i class="fa fa-search"></i></a>
                            {% if form.trigger.errors %}{{ form.trigger.errors.as_text }}{% endif %}
                        </div>
                    </div>
                    <div class="form-group" id="name-panel">
                        <label class="control-label">{{ form.name.label_tag }} <span class="required">*</span></label>
                        <div>
                            {{ form.name }}
                            {% if form.name.errors %}{{ form.name.errors.as_text }}{% endif %}
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="control-label">{{form.roll_up.label_tag}}</label>
                        {{form.roll_up}}
                    </div>
                    <div class="form-group">
                        <label class="control-label">{{form.roll_down.label_tag}}</label>
                        {{form.roll_down}}
                    </div>
                </div>
                <div class="col-md-2 col-md-offset-1">
                        <div class="form-group">
                            <label class="control-label">{{ form.severity.label_tag }} <span
                                    class="required">*</span></label>
                            <div>
                                {{ form.severity }}
                                {% if form.severity.errors %}{{ form.severity.errors.as_text }}{% endif %}
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="control-label">{{ form.details.label_tag }} <span
                                    class="required">*</span></label>
                            <div>
                                {{ form.details }}
                                {% if form.details.errors %}{{ form.details.errors.as_text }}{% endif %}
                            </div>
                        </div>
                    </div>
            </div>
            <div style="text-align:center" class="col-md-12"><h2>Mandatory Recipients</h2></div>
            <table id="trigger_sub" class="table table-striped table-bordered" width="60%">
            <thead>
                <tr>
                    <th rowspan="2" class="text-center">User</th>
                    <th class="text-center" colspan="2">Notify Immediately By</th>
                    <th class="text-center">Daily Summary</th>
                </tr>
                <tr>
                    <th class="text-center">
                        <label>
                            <input type="checkbox" id="select-all-email" />
                            Email
                        </label>
                    </th>
                    <th class="text-center">
                        <label>
                            <input type="checkbox" id="select-all-text" />
                            Text
                        </label>
                    </th>
                    <th class="text-center">
                        <label>
                            <input type="checkbox" id="select-all-summary" />
                            Email
                        </label>
                    </th>
                </tr>
            </thead>
            <tbody>
            {% for value, text in form.owner.field.choices %}
                {% if value %}
                <tr>
                    <td class="text-center">{{text}}</td>
                    <td class="text-center">
                        <input value="{{value}}" class="email_immediately" type="checkbox"{% if value in email_selected %} checked {% endif %} />
                    </td>
                    <td class="text-center">
                        <input value="{{value}}" class="text_immediately" type="checkbox" {% if value in text_selected %} checked {% endif %}/>
                    </td>
                    <td class="text-center">
                        <input value="{{value}}" class="email_daily" type="checkbox" {% if value in summary_selected %} checked {% endif %}/>
                    </td>
                </tr>
                {% endif %}
            {% endfor %}
            </tbody>
        </table>
            <a href="{% url 'asset.overview' asset.id deployment.code %}" id="btnCancel" class="btn btn-default">Cancel</a>
            <button type="submit" class="btn btn-primary">Save</button>
            <div id="trigger-detail" class="dialog-box"></div>
            <input type="hidden" id="email_notification" name="email_immediate" />
            <input type="hidden" id="text_notification" name="text_immediate" />
            <input type="hidden" id="email_summary" name="email_daily" />
        </form>
    </div>
</div>
{% endblock %}

{% block scripts %}
<script type="text/javascript">
    $(document).ready(function() {
        var groupDataId = 'group-{{ asset.group_id }}';
        var platformId = 'platform-{{ asset.platform_id }}';
        SetupCurrentSideNavMenu(groupDataId, platformId);
    });
    $(function(){
        $("#id_trigger").change(function(e){
            change_trigger();
        });

        $("#view-trigger").click(function(e) {
            var id = $("#id_trigger").val();
            var url = "{% url 'alert.view_trigger' 0 %}".replace(/\d+$/i, id);

            return open_dialog_box(e, '#trigger-detail', url);
        });

        function change_trigger(id) {
            var id = $("#id_trigger").val();
            var severitySelect = $("#id_severity");

            $("#name-panel").toggleClass('hide', (id != ''));
            $("#view-trigger").toggleClass('hide', (id == ''));

            if (id == '') {
                severitySelect.prop('disabled', false);
            } else {
                $.ajax({
                    type: "GET",
                    url: '/variable/ajax/get_trigger_by_id/' + id,
                    data: {},
                    success: function(response) {
                        severity_id = response.severity_id;
                        $('#id_severity option[value="' + severity_id + '"]');
                        severitySelect.prop('disabled', 'disabled');
                    }
                });
            }
        }

        init_trigger_dialog_box("#trigger-detail");
        change_trigger();
    });

    $(function() {
    $("#manual_alert_form").validate({
        rules: {
            name: "required",
            triggered_value: "required",
            details: "required"
        },
        messages: {
            name: "Name is required",
            triggered_value: "Triggered value is required",
            details: "Details are required"
        },
        errorElement: "em",
        errorPlacement: function (error, element) {
            // Add the `help-block` class to the error element
            error.addClass("help-block");
            if ( element.prop("type") === "checkbox" ) {
                error.insertAfter(element.parent("label"));
            } else {
                error.insertAfter(element);
            }
        },
        highlight: function (element, errorClass, validClass ) {
            $(element).closest(".form-group").addClass("has-error");
        },
        unhighlight: function (element, errorClass, validClass) {
            $(element).closest(".form-group").removeClass("has-error");
        }
    });
        $("#manual_alert_form").submit(function(e) {
            var variables = [];
            var email_immediate = [];
            var text_immediate = [];
            var email_daily = [];
            var isValid = true;

            $(".email_immediately:checkbox:checked").each(function() {;
                email_immediate.push($(this).val());
            });

            $(".text_immediately:checkbox:checked").each(function() {
                text_immediate.push($(this).val());
            });

            $(".email_daily:checkbox:checked").each(function() {
                email_daily.push($(this).val());
            });

    		if (!isValid) {
    		    e.preventDefault();
            }

            $("#email_notification").val(email_immediate);
    		$("#text_notification").val(text_immediate);
    		$("#email_summary").val(email_daily);
    		return true;
        });
    });

    $("#select-all-email").change(function() {
        if(this.checked) {
            $(".email_immediately").prop("checked", true);
        } else {
            $(".email_immediately").prop("checked", false);
        }
    });
    $("#select-all-text").change(function() {
        if(this.checked) {
            $(".text_immediately").prop("checked", true);
        } else {
            $(".text_immediately").prop("checked", false);
        }
    });
    $("#select-all-summary").change(function() {
        if(this.checked) {
            $(".email_daily").prop("checked", true);
        } else {
            $(".email_daily").prop("checked", false);
        }
    });

</script>
{% endblock %}