code/webapp/core/urls.py
from django.conf.urls import url
from django.contrib.auth import views as auth_views
from django.conf import settings

from .forms.account import LoginForm
from .views import account, dashboard, alert, asset, plots, variable, plot

urlpatterns = [

    # /account
    url(r'^account/login/?$',
        auth_views.login,
        {
            'template_name': 'account/login.html',
            'authentication_form': LoginForm,
        },
        name='account.login'),
    url(r'^account/logout/?$', auth_views.logout, {'next_page':settings.LOGIN_URL}, name='account.logout'),
    url(r'^account/myaccount/?$', account.my_account, name='account.my_account'),
    url(r'^account/preferences/?$', account.preferences, name='account.preferences'),
    url(r'^account/users/?$', account.users, name='account.users'),
    url(r'^account/default', account.default_page, name='account.default'),
    url(r'^account/edit_user/(?P<user_id>[^/.]*)/?', account.my_account, name='account.edit_user'),
    url(r'^account/add_user/?', account.my_account, name='account.add_user'),
    url(r'^account/delete_user', account.delete_user, name='account.delete_user'),
    url(r'^account/ajax/users', account.user_list, name='account.user_list'),

    # /dashboard
    url(r'^hotlist/?$', dashboard.overview, name='overview'),
    url(r'^dashboard/?$', dashboard.default_check, name='default_check'),
    url(r'^system/(?P<group_id>\d+)?$', dashboard.system_overview, name='dashboard.system_overview'),
    url(r'^system/ajax/system_overview_preference', dashboard.update_system_overview_preference, name='dashboard.update_system_overview_preference'),
    url(r'^system/power/(?P<platform_id>[^/.]+)/?', dashboard.power_details, name='dashboard.power_details'),
    url(r'^system/ajax/update_alert_disposition', dashboard.update_alert_by_disposition, name='dashboard.update_alert_by_disposition'),

    url(r'^system/backup_database', dashboard.backup_database, name='dashboard.backup_database'),
    url(r'^system/execute_backup_database', dashboard.execute_backup_database, name='dashboard.execute_backup_database'),

    # /alert
    url(r'^alert/resolve/(?P<alert_id>[^/.]+)/?', alert.resolve_alert_view, name='alert.resolve'),
    url(r'^alert/acknowledge/?', alert.acknowledge, name='alert.acknowledge'),
    url(r'^alert/update_status/?', alert.update_status, name='alert.update_status'),
    url(r'^alert/(?P<alert_id>\d+)/$', alert.detail, name='alert.detail'),
    url(r'^alert/(?P<alert_id>\d+)/(?P<is_resolve>[^/.]+)/?', alert.detail, name='alert.detail'),
    url(r'^alert/save_note/(?P<alert_id>\d+)/?', alert.save_note, name='alert.save_note'),
    url(r'^alert/ajax/get_notes/(?P<alert_id>\d+)/?', alert.get_notes, name='alert.get_notes'),
    url(r'^alert/ajax/get_occurrences/(?P<alert_id>\d+)/?', alert.get_occurrences, name='alert.get_occurrences'),
    url(r'^alert/ajax/view_trigger/(?P<trigger_id>[^/.]+)/?', alert.view_trigger, name='alert.view_trigger'),
    url(r'^alert/ajax/hotlist_alert_list/(?P<user_id>[^/.]+)/?', alert.hotlist_alert_list, name='alert.hotlist_alert_list'),
    url(r'^alert/create_manual/(?P<asset_id>[^/.]+)/(?P<deployment_code>[^/.]+)/?', alert.create_manual, name='alert.create_manual'),
    url(r'^alert/manage_subscriptions/(?P<asset_id>\d+)/?', alert.manage_subscriptions, name='alert.manage_subscriptions'),
    url(r'^alert/edit_trigger/(?P<trigger_id>\w+)/(?P<asset_id>\w+)/$', alert.edit_trigger, name='alert.edit_trigger'),
    url(r'^alert/edit_trigger/(?P<trigger_id>[^/.]+)/?', alert.edit_trigger, name='alert.edit_trigger'),
    url(r'^alert/edit_trigger/?$', alert.edit_trigger, name='alert.edit_trigger'),
    url(r'^alert/clone_trigger/(?P<trigger_id>[^/.]+)/?', alert.clone_trigger_page, name='alert.clone_trigger_page'),
    url(r'^alert/execute_clone_trigger/?', alert.execute_clone_trigger, name='alert.execute_clone_trigger'),
    url(r'^alert/manage_triggers/?$', alert.manage_triggers, name='alert.manage_triggers'),
    url(r'^alert/ajax/trigger_list/?$', alert.trigger_list, name='alert.trigger_list'),
    url(r'^alert/ajax/delete_trigger/?$', alert.delete_trigger, name='alert.delete_trigger'),
    url(r'^alert/ajax/purge_trigger/?$', alert.purge_trigger, name='alert.purge_trigger'),
    url(r'^alert/ajax/trigger_variable_list/(?P<trigger_id>[^/.]+)/?', alert.trigger_variable_list, name='alert.trigger_variable_list'),
    url(r'^alert/ajax/saved_variable_list/?', alert.saved_variables_list, name='alert.saved_variables_list'),
    url(r'^alert/ajax/alert_notification_list/(?P<alert_id>[^/.]+)/?', alert.alert_notification_list, name='alert.alert_notification_list'),
    url(r'^alert/ajax/hotlist_alert_list/(?P<user_id>[^/.]+)/?', alert.hotlist_alert_list, name='alert.hotlist_alert_list'),
    url(r'^alert/ajax/get_trigger_by_id/(?P<trigger_id>[^/.]+)/?', alert.get_trigger_by_id, name='alert.get_trigger_by_id'),
    url(r'^alert/create_redmine_issue/(?P<alert_id>\d+)/?$', alert.create_redmine_issue, name='alert.create_redmine_issue'),
    url(r'^alert/confirm_redmine_issue/(?P<alert_id>\d+)/?$', alert.confirm_redmine_issue, name='alert.confirm_redmine_issue'),
    url(r'^alert/ajax/redmine_trackers/(?P<project_id>\d+)/?$', alert.redmine_trackers, name='alert.redmine_trackers'),
    url(r'^alert/ajax/redmine_tracker_details/(?P<tracker_id>\d+)/?$', alert.redmine_tracker_details, name='alert.redmine_tracker_details'),
    url(r'^alert/ajax/refresh_notifications/?', alert.refresh_notifications, name='alert.refresh_notifications'),
    url(r'^redmine/confirm_redmine_issue/(?P<issue_id>\d+)/?$', alert.confirm_redmine, name='redmine.confirm_redmine'),

    # /asset
    url(r'^asset/overview/(?P<asset_id>[^/.]+)/(?P<deployment_code>[^/.]+)/?', asset.overview, name='asset.overview'),
    url(r'^asset/group/(?P<group_id>[^/.]+)/?', asset.group_overview, name='asset.group_overview'),
    url(r'^asset/map/(?P<group_id>[^/.]+)/?', asset.group_mooring_locations, name='asset.group_mooring_locations'),
    url(r'^asset/plot-data/?', asset.plot_data, name='asset.plot_data'),
    url(r'^asset/ajax/alert_history_data', asset.ajax_alert_history_data, name='asset.ajax_alert_history_data'),
    url(r'^asset/ajax/status_history_data/(?P<asset_id>\d+)', asset.ajax_status_history_data, name='asset.ajax_status_history_data'),
    url(r'^asset/picker/(?P<asset_id>[^/.]+)/(?P<name>[^/.]+)/?', asset.picker, name='asset.picker'),
    url(r'^asset/status_grid/(?P<platform_id>\d+)', asset.status_grid, name='asset.status_grid'),
    url(r'^asset/gliders/(?P<group_id>\d+)', asset.glider_overview, name='asset.glider_overview'),
    url(r'^asset/clone/(?P<asset_id>[^/.]+)/?', asset.clone_asset, name='asset.clone_asset'),
    url(r'^asset/execute_clone_asset/?', asset.execute_clone_asset, name='asset.execute_clone_asset'),
    url(r'^asset/purge_asset/(?P<asset_id>[^/.]+)/(?P<deployment_code>[^/.]+)/?', asset.purge_asset, name='asset.purge_asset'),
    url(r'^asset/execute_purge_asset/?', asset.execute_purge_asset, name='asset.execute_purge_asset'),
    url(r'^asset/platforms/?', asset.manage_platforms, name='asset.manage_platforms'),
    url(r'^asset/edit_platform/(?P<platform_id>\d+)', asset.edit_platform, name='asset.edit_platform'),
    url(r'^asset/edit_platform//?', asset.edit_platform, name='asset.edit_platform'),
    url(r'^asset/ajax/platform_list', asset.platform_list, name='asset.platform_list'),
    url(r'^asset/ajax/asset_subcategories', asset.subcategories, name='asset.subcategories'),
    url(r'^asset/import-platform', asset.import_platform, name='asset.import_platform'),
    url(r'^asset/ajax/reload-configuration', asset.reload_configuration, name='asset.reload_configuration'),
    url(r'^asset/ajax/purge-alerts', asset.purge_alerts, name='asset.purge_alerts'),
    url(r'^asset/edit-dataset/(?P<asset_id>[^/.]+)/(?P<deployment_code>[^/.]+)/?', asset.edit_dataset, name='asset.edit_dataset'),
    url(r'^asset/ajax/asset_variables', asset.asset_variables, name='asset.asset_variables'),
    url(r'^asset/ajax/update_erddap', asset.update_erddap, name='asset.update_erddap'),

    # /plot
    url(r'^asset/ajax/get_asset_variables/?', plots.get_asset_variables, name='plots.get_asset_variables'),
    url(r'^asset/ajax/delete_custom_plot/?', plots.delete_custom_plot, name='plots.delete_custom_plot'),
    url(r'^asset/edit_plot/(?P<asset_id>[^/.]+)/(?P<deployment_code>[^/.]+)/?$',plots.edit_plot, name='plots.edit_plot'),
    url(r'^asset/edit_plot/(?P<asset_id>[^/.]+)/(?P<deployment_code>[^/.]+)/(?P<plot_id>[^/.]+)/?',plots.edit_plot, name='plots.edit_plot'),
    url(r'^asset/clone_plot/(?P<asset_id>[^/.]+)/(?P<deployment_code>[^/.]+)/(?P<plot_id>[^/.]+)/?',plots.clone_plot_page, name='plots.clone_plot_page'),
    url(r'^plot/execute_clone_plot/?', plots.execute_clone_plot, name='plots.execute_clone_plot'),
    url(r'^plot/manage_plots/?',plots.manage_plots, name='plots.manage_plots'),
    url(r'^plot_list/ajax/plot_list/?', plots.plot_list, name='plots.plot_list'),
    url(r'^get_plot_info/ajax/get_plot_info/?', plots.get_plot_info, name='plots.get_plot_info'),

    # /plot pages
    url(r'^asset/plot_list/(?P<asset_id>[^/.]+)', plot.plot_list, name='plot.plot_list'),
    url(r'^asset/save_plot_page', plot.save_plot_page, name='plot.save_plot_page'),
    url(r'asset/plot_page/(?P<plot_page_id>[^/.]+)/?', plot.plot_page, name='plot.plot_page'),
    url(r'plot/shared/(?P<share_code>[^/.]+)', plot.plot_page, name='plot.shared_plot_page'),
    url(r'asset/import_plot_page', plot.import_plot_page, name='plot.import_plot_page'),
    url(r'asset/ajax/share_plot_page', plot.share_plot_page, name='plot.share_plot_page'),
    url(r'asset/ajax/disable_sharing', plot.disable_sharing, name='plot.disable_sharing'),
    url(r'^asset/ajax/plot_list_by_asset', plot.plot_list_by_asset, name='plot.plot_list_by_asset'),
    url(r'^plot_page/ajax/delete_plot_page', plot.delete_plot_page, name='plot.delete_plot_page'),

code/webapp/webapp/urls.py
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.contrib import admin
from django.http import HttpResponseRedirect
from django.conf import settings

urlpatterns = [
    url(r'^$', lambda r: HttpResponseRedirect(settings.DASHBOARD_URL)),
    url(r'^admin/', admin.site.urls),
    url(r'^settings/', include('livesettings.urls')),
    url(r'^', include('core.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

code/webapp/core/forms/asset.py
from django import forms

from ..models.asset import AssetDisposition, AssetDispositions, AssetCategory, AssetSubcategory

class PlatformForm(forms.Form):
    disposition = forms.ChoiceField()
    category = forms.ChoiceField()
    subcategory = forms.ChoiceField(required=False)

    deployment_date = forms.CharField(required=False, label='Deployment Date', widget=forms.DateTimeInput(attrs={'class': 'datetimepicker deployment_date'}, format="%m/%d/%y %I:%M%p"))
    recovery_date = forms.CharField(required=False, label='Recovery Date', widget=forms.DateTimeInput(attrs={'class': 'datetimepicker recovery_date'}, format="%m/%d/%y %I:%M%p"))

    lat = forms.FloatField(required=False, widget=forms.TextInput())
    lon = forms.FloatField(required=False, widget=forms.TextInput())

    depth = forms.FloatField(required=False, widget=forms.TextInput())

    def __init__(self, *args, **kwargs):
        super(PlatformForm, self).__init__(*args, **kwargs)

        self.fields['disposition'] = forms.ChoiceField(
            choices=tuple(AssetDisposition.objects.all().values_list('id', 'name')),
            widget=forms.Select(attrs={'class': 'form-control'})
        )

        categories = AssetCategory.objects.all().values_list("id", "name")
        categories = [(0, "Select a Category")] + list(categories)

        self.fields['category'] = forms.ChoiceField(
            choices=categories,
            widget=forms.Select(attrs={'class': 'form-control'}),
            required=False
        )

        subcategories = AssetSubcategory.objects.all().values_list("id", "name")
        subcategories = [(0, "Select a Subcategory")] + list(subcategories)

        self.fields['subcategory'] = forms.ChoiceField(
            choices=subcategories,
            widget=forms.Select(attrs={'class': 'form-control'}),
            required=False
        )
    
    def clean(self):
        
        self.cleaned_data = super(PlatformForm, self).clean()
        if (self.cleaned_data.get('lat') and not self.cleaned_data.get('lon') or
            self.cleaned_data.get('lon') and not self.cleaned_data.get('lat')):
            raise forms.ValidationError("Please enter both Latitude and Longitude")

        return self.cleaned_data


class ImportPlatformForm(forms.Form):
    platform_code = forms.CharField(max_length=30, widget=forms.TextInput(attrs={'class': 'form-control'}))
    deployment_code = forms.CharField(max_length=30, widget=forms.TextInput(attrs={'class': 'form-control'}))
    disposition = forms.ModelChoiceField(
        queryset=AssetDisposition.objects.all(),
        required=False,
        empty_label=None,
        widget=forms.Select(attrs={'class': 'form-control'}))
    category = forms.ChoiceField(required=False)
    subcategory = forms.ChoiceField(required=False)

    def __init__(self, *args, **kwargs):
        super(ImportPlatformForm, self).__init__(*args, **kwargs)

        cats = AssetCategory.objects.all()
        cat = []
        cat.append([0, 'Select a Category'])
        for c in cats:
            cat.append([c.id, c.name])

        self.fields['category'] = forms.ChoiceField(
            choices=tuple(cat),
            widget=forms.Select(attrs={'class': 'form-control'}),
            required=False
        )
        subcat = []
        subcat.append([0, 'Select a Subcategory'])
        subcats = AssetSubcategory.objects.all()
        for sub in subcats:
            subcat.append([sub.id, sub.name])
        self.fields['subcategory'] = forms.ChoiceField(
            choices=tuple(subcat),
            widget=forms.Select(attrs={'class': 'form-control'}),
            required=False
        )

code/webapp/templates/asset/glider_overview.html
{% extends 'base.html' %}
{% load static %}
{% load ui_tags status_tags %}

{% block topnav %}
<h1>{{ group.name }}</h1>
{% endblock %}

{% block content %}
<div class="clearfix"></div>
{% for num, group in plat_dict.items %}
<div class="row row-eq-height">
    {% for glider in group %}
    {% for glider_name, all_glider_data in glider.items %}
    <div class="col-lg-4">
        <div class="x_panel glider">
            <div class="x_title">
                <h2>{{ glider_name }} {% if all_glider_data.latest_time %}({{ all_glider_data.latest_time|date:"n/j/y"|lower }}){% endif %}</h2>
                <div class="clearfix"></div>
            </div>
            {% for asset in all_glider_data.glider_deployments %}
            <div class="x_content">
                <div class="row">
                    <div class="col-lg-3">
                        <div>
                            {# last_update could be None or some date #}
                            {% if asset.last_update and asset.is_data_recent %}
                                <i class="fa fa-circle circle-glider-status-ok glider-status-circle"
                                    title="Updated: {% if asset.last_update %}{{asset.last_update|date:'n/j/y'|lower}}{% endif %}">
                                </i>
                            {% else %}
                                <i class="fa fa-circle circle-status-error glider-status-circle"
                                   title="Updated: {% if asset.last_update %}{{asset.last_update|date:'n/j/y'|lower}}{% else %}data not available{% endif %}">
                                </i>
                            {% endif %}
                            {{asset.deployment.name}}
                        </div>
                    </div>
                    <div class="col-lg-9 text-right glider-links">
                        <a href="{{ asset.erddap_data_url }}" target="_blank">ERDDAP Data</a> |
                        <a href="{{ asset.erddap_graph_url }}" target="_blank">ERDDAP Graphs</a>
                        {% if asset.raw_data_dir %}
                        | <a href="{{ asset.raw_data_dir }}" target="_blank">Raw Data</a>
                        {% endif %}
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
    {% endfor %}
    {% endfor %}
</div>
{% endfor %}


{% endblock %}

code/webapp/templates/asset/group_overview.html
{% extends 'base.html' %}
{% load static %}
{% load ui_tags status_tags %}

{% block topnav %}
<h1>{{ group.name }}</h1>
{% endblock %}

{% block content %}

<style type="text/css">
	button.accordion {
		background-color: #5f9ea0;
		color: white;
		cursor: pointer;
		padding: 18px;
		width: 100%;
		border: 1px solid black;
		text-align: left;
		outline: none;
		font-size: 15px;
		transition: 0.4s;
	}

	button.accordion.active, button.accordion:hover {
		background-color: #6495ED;
	}

	div.panel {
		padding: 0 18px;
		background-color: white;
		max-height: 0;
		overflow: hidden;
		transition: max-height 0.2s ease-out;
	}

</style>
<div class="row">
    <div class="row disposition-filters" id="dispositions">
        <div class="col-md-6 text-left">
            Displayed Platforms:
            {% for disposition in dispositions %}
            <label>
                <input
                        type="checkbox"
                        data-value="{{ disposition.id }}"
                        {% if disposition.id in shown_dispositions %}checked="checked"{% endif %} />
                {{ disposition.name }}
            </label>
            {% endfor %}
        </div>
    </div>
</div>
{% for platform in platforms %}
    <div class="col-lg-6 {% if not platform.disposition_id in shown_dispositions %}hide{% endif %}"
        data-disposition-id="{{ platform.disposition_id }}">
        <div class="x_panel">
            <div class="x_title">
                <div class="col-sm-4 text-left">
                    <h2>
                        <a href="{% url 'asset.overview' platform.platform_id platform.deployment_code %}">
                            {{ platform.platform_code }} ({{ platform.deployment_code }})
                        </a>
                    </h2>
                </div>
                <div class="col-sm-4 text-center">
                    <h2 class="title-no-float">Active Alerts: {{ platform.alerts }}</h2>
                </div>
                <div class="col-sm-4 col-no-horiz-padding text-right">
                    <ul class="panel_toolbox nav">
                        <li>
                            <a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                        </li>
                    </ul>
                </div>
                <div class="clearfix"></div>
            </div>
            <div class="x_content">
                {% status_grid platform.platform_id platform.platform_id platform.deployment_code %}
            </div>
        </div>
    </div>
{% endfor %}

{% endblock %}

{% block scripts %}

<script type="text/javascript">
    $(document).ready(function() {
        var groupDataId = 'group-{{ group.id }}';
        SetupCurrentSideNavMenu(groupDataId, null);

        $("#dispositions input[type=checkbox]").click(function(){
            $("#dispositions input[type=checkbox]").each(function(){
                var id = $(this).attr('data-value');
                $("div[data-disposition-id=" + id + "]").toggleClass('hide', !$(this).is(":checked"));
            });
        });
    });
	</script>

{% endblock %}

code/webapp/templates/asset/import_platform.html
{% extends 'base.html' %}
{% load static %}

{% block topnav %}
    <h1>Import Platform</h1>
{% endblock %}

{% block content %}
<div class="x_panel">
    <div class="x_content">

        <form method="post" class="form-horizontal form-label-left" id="import-form">
            <input type="hidden" name="confirmed" id="confirmed" />
            {% csrf_token %}

        <div class="row">
            <div class="col-md-5">
                <div class="x_panel">
                    <div class="x_title">Platform Details</div>
                    <div class="x_content">
                        <div class="form-group">
                            <label class="control-label col-md-4">Platform Code</label>
                            <div class="col-md-8">
                                {% if ready_for_import %}
                                    <div class="form-control-static">{{ form.platform_code.value|default_if_none:"" }}</div>
                                    <input type="hidden" name="platform_code" value='{{ form.platform_code.value|default_if_none:"" }}' />
                                {% else %}
                                    <span class="form-control-static">{{ form.platform_code }}</span>
                                {% endif %}
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="control-label col-md-4">Deployment Code</label>
                            <div class="col-md-8">
                                {% if ready_for_import %}
                                    <div class="form-control-static">{{ form.deployment_code.value|default_if_none:"" }}</div>
                                    <input type="hidden" name="deployment_code" value='{{ form.deployment_code.value|default_if_none:"" }}' />
                                {% else %}
                                    <span class="form-control-static">{{ form.deployment_code }}</span>
                                {% endif %}
                            </div>
                        </div>
                        {% if ready_for_import %}
                        <div class="form-group">
                            <label class="control-label col-md-4">Category</label>
                            <div class="col-md-8">
                                {{ form.category }}
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="control-label col-md-4">Subcategory</label>
                            <div class="col-md-8">
                                {{ form.subcategory }}
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="control-label col-md-4">Disposition</label>
                            <div class="col-md-8">
                                {{ form.disposition }}
                                <p class='invalid-input'>{% if form.disposition.errors %}{{ form.disposition.errors.as_text }}{% endif %}</p>
                            </div>
                        </div>
                        {% endif %}
                        {% if not ready_for_import %}
                        <div class="form-group">
                            <label class="control-label col-md-4"></label>
                            <div class="col-md-8">
                                <button type="submit" class="btn btn-primary btn-sm">Verify Information</button>
                            </div>
                        </div>
                        {% endif %}
                    </div>
                </div>
            </div>
            {% if verified %}
            <div class="col-md-6">
                {% csrf_token %}
                {% if existing_asset and not import_succeeded %}
                <div class="alert alert-info text-center">
                    The selected platform/deployment has already been imported. <br />You can view the platform below, or proceed with importing the new platform config and overwrite the existing platform.
                </div>
                <div class="text-center">
                    <a href="{% url 'asset.overview' existing_asset.id existing_asset.deployment.code %}" class="btn btn-primary btn-sm">View Platform</a>
                    <button type="submit" class="btn btn-danger btn-sm" id="confirm-import">Import Platform/Mooring</button>
                </div>
                {% endif %}

                {% if missing_config %}
                <div class="alert alert-danger text-center">
                    A platform configuration file for the platform/deployment could not be located
                </div>
                {% endif %}

                {% if ready_for_import %}
                <div class="alert well">
                    <p>A platform configuration file was found for this platform/deployment, and it has not already be imported. Please review the configuration file and data before completing the import process</p>
                    <br />
                    <div class="text-center">
                        <a href="{{ data_url }}" target="_blank" class="btn btn-default btn-sm">View Data Directory</a>
                        <a href="{{ config_url }}" target="_blank" class="btn btn-default btn-sm">View Platform Config</a>
                        <button type="submit" class="btn btn-primary btn-sm" id="confirm-import">Import Platform/Mooring</button>
                    </div>

                    <div id="import-platform-loading">
                        <p>Importing platform from the platform configuration file. Please wait...</p>
                        <img src="{% static 'images/loading.gif' %}" />
                    </div>
                </div>
                {% endif %}

                {% if import_failed %}
                <div class="alert alert-danger text-center">
                    <p>The platform/deployment failed to import: {{ import_message }}</p>
                </div>
                {% endif %}

                {% if import_succeeded %}
                <div class="alert alert-success text-center">
                    <p>The platform/deployment has been successfully imported</p>
                </div>
                <p class="text-center">
                    <a href="{% url 'asset.overview' new_asset.id new_asset.deployment.code %}" class="btn btn-primary btn-sm">View Platform</a>
                </p>
                {% endif %}
            </div>
            {% endif %}
        </div>

        </form>
    </div>
</div>
{% endblock %}

{% block scripts %}
<script>
    $("#id_category").on('change', function() {
        var id = $("#id_category option:selected").val();
        getSubcategories(id, 0);
    });

    $(function() {
        $("#confirm-import").click(function(){
            $("#import-platform-loading").show();
            $("#confirmed").val(true);

            return true;
        });

        $("#import-form").submit(function(){
            if ($("#confirmed").val() == "true") {
                $(this).attr('disabled','disabled');
            }
        });

        var flag = '{{ update_successful }}';
        if($("#id_category option:selected").val() != '0') {
            var id = $("#id_category option:selected").val();
            var sub_id = $("#id_subcategory option:selected").val();
            getSubcategories(id, sub_id);
        }
        else if(flag != 'True' && $("#id_category option:selected").val() == '0') {
            $("#id_subcategory").find('option').remove();
            $("#id_subcategory").append($('<option value="0">Select a Subcategory</option>'));
        }


        {% if ready_for_import %}
            $("#id_disposition").val({{ default_disposition }});
        {% endif %}
    });

    function getSubcategories(id, selected) {
        if (id === "")
            return;

        $.ajax({
            url: "{% url 'asset.subcategories' %}",
            method: 'POST',
            data: { 'id': id },
            success: function(response) {
                $("#id_subcategory").find('option').remove();

                if (response.data && response.data.length > 0)
                {
                    for (var i = 0; i < response.data.length; i++) {
                        var subcategory = response.data[i];
                        var selectedAttr =  subcategory.id == selected ? " selected" : "";

                        $("#id_subcategory").append(
                            $("<option value='" + subcategory.id + "'" + selectedAttr + ">" + subcategory.name + "</option>")
                        );
                    }
                }
            }
        });
    };


</script>
{% endblock %}

code/webapp/templates/asset/status_grid.html
{% load status_tags %}
{% status_grid platform.id platform.id platform.deployment.code callback=callback show_platform=True %}